# Generated by Django 4.1.5 on 2023-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'verbose_name': 'Технику', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterField(
            model_name='tech',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
